# Setup
title: Yiteng Wang
url: https://www.wangyiteng.co.uk/
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-190330073-1

# Specify the author for blog posts
author:
  name: Yiteng Wang
  url: https://instagram.com/andwong.insta
  email: yiteng.wang@outlook.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: 目录
    url: /archive

  - title: 关于我
    url: /about
    
  - title: 隐私条款
    url: /Privacy
    
